---
- name: "Directory Exists | {{ elasticsearch_runtime_root }}"
  file:
    state: directory
    path: "{{ elasticsearch_runtime_root }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - elasticsearch
