---
- name: Removing Plugins if they exist
  command: "bin/plugin --remove {{ item.name }}"
  args: 
    chdir: /usr/share/elasticsearch
  with_items: elasticsearch_plugins
  ignore_errors: yes

- name: Installing Plugins by Name
  command: "bin/plugin --install {{ item.name }}"
  args: 
    chdir: /usr/share/elasticsearch
  with_items: elasticsearch_plugins
  ignore_errors: yes

- name: Installing Plugins by URL
  command: "bin/plugin --install {{ item.name }} --url {{ item.url }}"
  args: 
    chdir: /usr/share/elasticsearch
  when: item.url is defined
  with_items: elasticsearch_plugins
  ignore_errors: yes

- file:
    path: "/usr/share/elasticsearch/plugins" 
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    recurse: yes
