# ---
# - name: Removing Plugins if they exist
#   action: >
#     shell bin/plugin --remove {{ item.name }}
#     chdir={{ elasticsearch_home_dir }}
#   with_items: elasticsearch_plugins
#   ignore_errors: yes

# - name: Installing Plugins by Name
#   action: >
#     shell bin/plugin -install {{ item.name }}
#     chdir={{ elasticsearch_home_dir }}
#   when: item.url is not defined
#   with_items: elasticsearch_plugins
#   ignore_errors: yes

# - name: Installing Plugins by URL
#   action: >
#     shell bin/plugin -install {{ item.name }} -url {{ item.url }}
#     chdir={{ elasticsearch_home_dir }}
#   when: item.url is defined
#   with_items: elasticsearch_plugins
#   ignore_errors: yes

# - file:
#     path: "{{ elasticsearch_plugin_dir }}" 
#     state: directory
#     owner: "{{ elasticsearch_user }}"
#     group: "{{ elasticsearch_group }}"
#     recurse: yes
